version: "3.9"

services:
  web:
    build: .
    command: python manage.py runsslserver --certificate cert.pem --key key.pem
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - migration
  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/app
